/*
 * MATLAB Compiler: 4.0 (R14)
 * Date: Sun Sep 19 23:06:43 2010
 * Arguments: "-B" "macro_default" "-B" "csharedlib:libadc" "-W" "lib:libadc"
 * "-T" "link:lib" "-W" "lib:libadc" "-T" "link:lib" "AdcDynTest.m" "-v" 
 */


#ifdef __cplusplus
extern "C" {
#endif
const unsigned char __MCC_libadc_public_data[] = {'3', '0', '8', '1', '9',
                                                  'D', '3', '0', '0', 'D',
                                                  '0', '6', '0', '9', '2',
                                                  'A', '8', '6', '4', '8',
                                                  '8', '6', 'F', '7', '0',
                                                  'D', '0', '1', '0', '1',
                                                  '0', '1', '0', '5', '0',
                                                  '0', '0', '3', '8', '1',
                                                  '8', 'B', '0', '0', '3',
                                                  '0', '8', '1', '8', '7',
                                                  '0', '2', '8', '1', '8',
                                                  '1', '0', '0', 'C', '4',
                                                  '9', 'C', 'A', 'C', '3',
                                                  '4', 'E', 'D', '1', '3',
                                                  'A', '5', '2', '0', '6',
                                                  '5', '8', 'F', '6', 'F',
                                                  '8', 'E', '0', '1', '3',
                                                  '8', 'C', '4', '3', '1',
                                                  '5', 'B', '4', '3', '1',
                                                  '5', '2', '7', '7', 'E',
                                                  'D', '3', 'F', '7', 'D',
                                                  'A', 'E', '5', '3', '0',
                                                  '9', '9', 'D', 'B', '0',
                                                  '8', 'E', 'E', '5', '8',
                                                  '9', 'F', '8', '0', '4',
                                                  'D', '4', 'B', '9', '8',
                                                  '1', '3', '2', '6', 'A',
                                                  '5', '2', 'C', 'C', 'E',
                                                  '4', '3', '8', '2', 'E',
                                                  '9', 'F', '2', 'B', '4',
                                                  'D', '0', '8', '5', 'E',
                                                  'B', '9', '5', '0', 'C',
                                                  '7', 'A', 'B', '1', '2',
                                                  'E', 'D', 'E', '2', 'D',
                                                  '4', '1', '2', '9', '7',
                                                  '8', '2', '0', 'E', '6',
                                                  '3', '7', '7', 'A', '5',
                                                  'F', 'E', 'B', '5', '6',
                                                  '8', '9', 'D', '4', 'E',
                                                  '6', '0', '3', '2', 'F',
                                                  '6', '0', 'C', '4', '3',
                                                  '0', '7', '4', 'A', '0',
                                                  '4', 'C', '2', '6', 'A',
                                                  'B', '7', '2', 'F', '5',
                                                  '4', 'B', '5', '1', 'B',
                                                  'B', '4', '6', '0', '5',
                                                  '7', '8', '7', '8', '5',
                                                  'B', '1', '9', '9', '0',
                                                  '1', '4', '3', '1', '4',
                                                  'A', '6', '5', 'F', '0',
                                                  '9', '0', 'B', '6', '1',
                                                  'F', 'C', '2', '0', '1',
                                                  '6', '9', '4', '5', '3',
                                                  'B', '5', '8', 'F', 'C',
                                                  '8', 'B', 'A', '4', '3',
                                                  'E', '6', '7', '7', '6',
                                                  'E', 'B', '7', 'E', 'C',
                                                  'D', '3', '1', '7', '8',
                                                  'B', '5', '6', 'A', 'B',
                                                  '0', 'F', 'A', '0', '6',
                                                  'D', 'D', '6', '4', '9',
                                                  '6', '7', 'C', 'B', '1',
                                                  '4', '9', 'E', '5', '0',
                                                  '2', '0', '1', '1', '1'
                                                  , '\0'};

const char *__MCC_libadc_name_data = "libadc";

const char *__MCC_libadc_root_data = "";

const unsigned char __MCC_libadc_session_data[] = {'7', '3', 'C', 'D', '4',
                                                   'B', '9', '9', 'A', 'B',
                                                   '3', '5', 'D', 'D', '3',
                                                   '1', 'C', '5', '0', 'D',
                                                   '1', 'F', '7', 'E', 'A',
                                                   'A', 'A', 'D', '9', '0',
                                                   'C', '9', 'E', 'F', '2',
                                                   'E', 'F', '2', 'A', 'C',
                                                   '4', 'E', '3', 'B', 'C',
                                                   'A', '3', '1', 'E', '7',
                                                   '9', '8', '0', '4', '4',
                                                   '8', '3', '3', '6', '7',
                                                   '9', '4', '2', '9', 'E',
                                                   '4', '3', 'E', '8', '2',
                                                   'E', '3', '4', 'E', '5',
                                                   'C', 'E', 'B', '5', '7',
                                                   'F', '8', '6', 'C', '2',
                                                   'C', 'C', '7', '9', '3',
                                                   'C', '3', 'C', '9', '9',
                                                   '0', 'D', '7', 'E', '9',
                                                   '1', '7', '4', '7', 'F',
                                                   'C', 'F', 'B', '0', '4',
                                                   'E', '3', '7', '6', 'A',
                                                   'B', 'F', 'D', '6', 'E',
                                                   'B', '9', '4', '0', 'C',
                                                   '4', 'C', 'A', 'D', 'C',
                                                   '3', '0', '2', '8', 'E',
                                                   '6', '0', 'B', '8', 'A',
                                                   'F', '2', '8', 'D', '7',
                                                   '6', 'F', 'C', '7', 'C',
                                                   '6', '1', 'E', 'A', 'B',
                                                   '9', 'B', '4', 'D', '5',
                                                   'F', 'C', 'C', '7', '6',
                                                   '6', 'E', '3', '0', 'B',
                                                   'B', 'F', '7', '3', 'C',
                                                   'E', '7', 'B', '7', '1',
                                                   '3', '0', '2', 'E', '6',
                                                   '4', '0', '6', '0', '4',
                                                   '1', '3', '5', 'C', 'F',
                                                   '3', '0', 'A', 'A', '0',
                                                   'F', '5', 'E', '9', '8',
                                                   '5', 'E', 'D', '9', 'C',
                                                   '6', '1', 'C', '7', '0',
                                                   'C', '8', '9', '3', '7',
                                                   '5', 'D', '2', 'F', '6',
                                                   'C', '1', 'B', '5', '8',
                                                   '6', '7', 'F', '4', '0',
                                                   '9', 'D', '8', '9', '0',
                                                   '6', 'F', '7', '1', '0',
                                                   '2', '1', '7', 'F', 'A',
                                                   'B', '6', 'A', 'B', '5',
                                                   '2', '\0'};

const char *__MCC_libadc_matlabpath_data[] = {"libadc/",
                                              "toolbox/compiler/deploy/",
                                              "$TOOLBOXMATLABDIR/general/",
                                              "$TOOLBOXMATLABDIR/ops/",
                                              "$TOOLBOXMATLABDIR/lang/",
                                              "$TOOLBOXMATLABDIR/elmat/",
                                              "$TOOLBOXMATLABDIR/elfun/",
                                              "$TOOLBOXMATLABDIR/specfun/",
                                              "$TOOLBOXMATLABDIR/matfun/",
                                              "$TOOLBOXMATLABDIR/datafun/",
                                              "$TOOLBOXMATLABDIR/polyfun/",
                                              "$TOOLBOXMATLABDIR/funfun/",
                                              "$TOOLBOXMATLABDIR/sparfun/",
                                              "$TOOLBOXMATLABDIR/scribe/",
                                              "$TOOLBOXMATLABDIR/graph2d/",
                                              "$TOOLBOXMATLABDIR/graph3d/",
                                              "$TOOLBOXMATLABDIR/specgraph/",
                                              "$TOOLBOXMATLABDIR/graphics/",
                                              "$TOOLBOXMATLABDIR/uitools/",
                                              "$TOOLBOXMATLABDIR/strfun/",
                                              "$TOOLBOXMATLABDIR/imagesci/",
                                              "$TOOLBOXMATLABDIR/iofun/",
                                              "$TOOLBOXMATLABDIR/audiovideo/",
                                              "$TOOLBOXMATLABDIR/timefun/",
                                              "$TOOLBOXMATLABDIR/datatypes/",
                                              "$TOOLBOXMATLABDIR/verctrl/",
                                              "$TOOLBOXMATLABDIR/codetools/",
                                              "$TOOLBOXMATLABDIR/helptools/",
                                              "$TOOLBOXMATLABDIR/winfun/",
                                              "$TOOLBOXMATLABDIR/demos/",
                                              "toolbox/local/",
                                              "toolbox/compiler/",
                                              "toolbox/signal/signal/"};
const int __MCC_libadc_matlabpath_data_count = 33;

const char *__MCC_libadc_mcr_application_options[] = { "" };
const int __MCC_libadc_mcr_application_option_count = 0;
const char *__MCC_libadc_mcr_runtime_options[] = { "" };
const int __MCC_libadc_mcr_runtime_option_count = 0;
#ifdef __cplusplus
}
#endif


