###########################################################################
#
# Generated by : Version 8.0 Build 231 07/10/2008 Service Pack 1 SJ Full Version
#
# Project      : top
# Revision     : top
#
# Date         : Sun Apr 17 22:21:11 China Standard Time 2011
#
###########################################################################
 
 
# WARNING: Expected ENABLE_CLOCK_LATENCY to be set to 'ON', but it is set to 'OFF'
#          In SDC, create_generated_clock auto-generates clock latency
#
# ------------------------------------------
#
# Create generated clocks based on PLLs
derive_pll_clocks -use_tan_name
#
# ------------------------------------------


# Original Clock Setting Name: lvds_i:lvds_i_1|rx_inclock
create_clock -period "3.333 ns" \
             -name {rx_inclock_i} {rx_inclock_i}
# ---------------------------------------------


# Original Clock Setting Name: FX_CLK_i
create_clock -period "25.000 ns" \
             -name {FX_CLK_i} {FX_CLK_i}
# ---------------------------------------------


# Original Clock Setting Name: clk_80m
create_clock -period "8.000 ns" \
             -name {clk_80m} {clk_80m}
# ---------------------------------------------


# Original Clock Setting Name: had_rec:had_rec_2|demux:demux_1|lvds_i:\GEN_LVDS_IMPL:lvds_i_1|altlvds_rx:altlvds_rx_component|lvds_i_lvds_rx1:auto_generated|wire_pll_clk[0]
# WARNING: Ignoring OFFSET_FROM_BASE_CLOCK assignment for clock 'had_rec:had_rec_2|demux:demux_1|lvds_i:\GEN_LVDS_IMPL:lvds_i_1|altlvds_rx:altlvds_rx_component|lvds_i_lvds_rx1:auto_generated|wire_pll_clk[0]'
create_generated_clock -divide_by 4 -multiply_by 1  \
                       -source rx_inclock_i \
                       -name {had_rec:had_rec_2|demux:demux_1|lvds_i:\GEN_LVDS_IMPL:lvds_i_1|altlvds_rx:altlvds_rx_component|lvds_i_lvds_rx1:auto_generated|wire_pll_clk[0]} \
                       {had_rec:had_rec_2|demux:demux_1|lvds_i:\GEN_LVDS_IMPL:lvds_i_1|altlvds_rx:altlvds_rx_component|lvds_i_lvds_rx1:auto_generated|wire_pll_clk[0]}
# ---------------------------------------------


# Original Clock Setting Name: had_rec:had_rec_2|demux:demux_1|lvds_i:\GEN_LVDS_IMPL:lvds_i_1|altlvds_rx:altlvds_rx_component|lvds_i_lvds_rx1:auto_generated|wire_pll_sclkout[0]
# WARNING: Ignoring OFFSET_FROM_BASE_CLOCK assignment for clock 'had_rec:had_rec_2|demux:demux_1|lvds_i:\GEN_LVDS_IMPL:lvds_i_1|altlvds_rx:altlvds_rx_component|lvds_i_lvds_rx1:auto_generated|wire_pll_sclkout[0]'
create_generated_clock -multiply_by 1  \
                       -source rx_inclock_i \
                       -name {had_rec:had_rec_2|demux:demux_1|lvds_i:\GEN_LVDS_IMPL:lvds_i_1|altlvds_rx:altlvds_rx_component|lvds_i_lvds_rx1:auto_generated|wire_pll_sclkout[0]} \
                       {had_rec:had_rec_2|demux:demux_1|lvds_i:\GEN_LVDS_IMPL:lvds_i_1|altlvds_rx:altlvds_rx_component|lvds_i_lvds_rx1:auto_generated|wire_pll_sclkout[0]}
# ---------------------------------------------

# ** Clock Latency
#    -------------

# ** Clock Uncertainty
#    -----------------

# ** Multicycles
#    -----------
# ** Cuts
#    ----

# ** Input/Output Delays
#    -------------------




# ** Tpd requirements
#    ----------------

# ** Setup/Hold Relationships
#    ------------------------

# ** Tsu/Th requirements
#    -------------------


# ** Tco/MinTco requirements
#    -----------------------

#
# Entity Specific Timing Assignments found in
# the Timing Analyzer Settings report panel
#
set_false_path -from [get_keepers {*dcfifo_3lj1*|delayed_wrptr_g[*]}] -to [get_keepers {*dcfifo_3lj1*|*rs_dgwp|*dffpipe13|dffe14a[*]}]
set_false_path -from [get_keepers {*dcfifo_3lj1*|rdptr_g[*]}] -to [get_keepers {*dcfifo_3lj1*|*ws_dgrp|*dffpipe17|dffe18a[*]}]
set_false_path -from [get_keepers {*dcfifo_mvk1*|delayed_wrptr_g[*]}] -to [get_keepers {*dcfifo_mvk1*|*rs_dgwp|*dffpipe10|dffe11a[*]}]
set_false_path -from [get_keepers {*dcfifo_mvk1*|rdptr_g[*]}] -to [get_keepers {*dcfifo_mvk1*|*ws_dgrp|*dffpipe14|dffe15a[*]}]
set_multicycle_path -setup -start 4 -from [get_keepers {*lvds_i_lvds_rx1*|wire_rx_dataout*}] -to [get_keepers {*lvds_i_lvds_rx1*|rxreg*}]
set_multicycle_path -hold -start 3 -from [get_keepers {*lvds_i_lvds_rx1*|wire_rx_dataout*}] -to [get_keepers {*lvds_i_lvds_rx1*|rxreg*}]


# ---------------------------------------------
# The following clock group is added to try to 
# match the behavior of:
#   CUT_OFF_PATHS_BETWEEN_CLOCK_DOMAINS = ON
# ---------------------------------------------

set_clock_groups -asynchronous \
                 -group { \
                       had_rec:had_rec_2|demux:demux_1|lvds_i:\GEN_LVDS_IMPL:lvds_i_1|altlvds_rx:altlvds_rx_component|lvds_i_lvds_rx1:auto_generated|wire_pll_clk[0] \
                       had_rec:had_rec_2|demux:demux_1|lvds_i:\GEN_LVDS_IMPL:lvds_i_1|altlvds_rx:altlvds_rx_component|lvds_i_lvds_rx1:auto_generated|wire_pll_sclkout[0] \
                       rx_inclock_i \
                        } \
                 -group { \
                       had_rec:had_rec_2|dat_buf:dat_buf_1|dcm45:dcm45_1|altpll:altpll_component|_clk0 \
                       clk_80m \
                        } \
                 -group { \
                       tlc3548:tlc3548_1|dcm_1M:dcm_1M_1|altpll:altpll_component|_clk0 \
                       dcm_user:dcm_user_1|altpll:altpll_component|_clk0 \
                       FX_CLK_i \
                        } \

# ---------------------------------------------

