-- hds header_start
--
-- VHDL Architecture ac210_freqdet.dff_en_r_pline_w.untitled
--
-- Created:
--          by - pfmaistre.UNKNOWN (RED021W2K)
--          at - 17:30:04 01/27/04
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2002.1b (Build 7)
--
-- hds header_end
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;
USE ieee.std_logic_unsigned.all;

ENTITY dff_en_r_pline_w IS
   GENERIC( 
      Pipeline : integer := 8
   );
   PORT( 
      Clk    : IN     std_logic;
      Clear  : IN     std_logic  := '0';
      D      : IN     std_logic_vector;
      Enable : IN     std_logic  := '1';
      Q      : OUT    std_logic_vector
   );

-- Declarations

END dff_en_r_pline_w ;

-- hds interface_end
ARCHITECTURE untitled OF dff_en_r_pline_w IS
	CONSTANT Size : natural := D'length;
	CONSTANT Mask : std_logic_vector(Size-1 DOWNTO 0) := (others => '0');
	type t_int_reg is array (0 to Pipeline) of std_logic_vector(Size-1 DOWNTO 0);
	signal int_reg : t_int_reg ;
BEGIN
ShReg: process (Clk, Clear)		
	begin
		if Clear = '1' then
			for i in 0 to Pipeline loop
	     		int_reg(i) <= (others => '0');
	        end loop;
		elsif rising_edge(Clk) then
			if Enable = '1'  then
				int_reg(Pipeline)        <= D;
		    		int_reg(0 to Pipeline-1) <= int_reg(1 to Pipeline);
		    end if;	    
	    end if;	    
	end process ShReg;
	Q <= int_reg(0);
END untitled;
