/*
 * MATLAB Compiler: 4.0 (R14)
 * Date: Sun Sep 19 00:24:48 2010
 * Arguments: "-B" "macro_default" "-B" "csharedlib:libalgo" "-W" "lib:libalgo"
 * "-T" "link:lib" "-W" "lib:libalgo" "-T" "link:lib" "ddc_func" "-v" 
 */


#ifdef __cplusplus
extern "C" {
#endif
const unsigned char __MCC_libalgo_public_data[] = {'3', '0', '8', '1', '9',
                                                   'D', '3', '0', '0', 'D',
                                                   '0', '6', '0', '9', '2',
                                                   'A', '8', '6', '4', '8',
                                                   '8', '6', 'F', '7', '0',
                                                   'D', '0', '1', '0', '1',
                                                   '0', '1', '0', '5', '0',
                                                   '0', '0', '3', '8', '1',
                                                   '8', 'B', '0', '0', '3',
                                                   '0', '8', '1', '8', '7',
                                                   '0', '2', '8', '1', '8',
                                                   '1', '0', '0', 'C', '4',
                                                   '9', 'C', 'A', 'C', '3',
                                                   '4', 'E', 'D', '1', '3',
                                                   'A', '5', '2', '0', '6',
                                                   '5', '8', 'F', '6', 'F',
                                                   '8', 'E', '0', '1', '3',
                                                   '8', 'C', '4', '3', '1',
                                                   '5', 'B', '4', '3', '1',
                                                   '5', '2', '7', '7', 'E',
                                                   'D', '3', 'F', '7', 'D',
                                                   'A', 'E', '5', '3', '0',
                                                   '9', '9', 'D', 'B', '0',
                                                   '8', 'E', 'E', '5', '8',
                                                   '9', 'F', '8', '0', '4',
                                                   'D', '4', 'B', '9', '8',
                                                   '1', '3', '2', '6', 'A',
                                                   '5', '2', 'C', 'C', 'E',
                                                   '4', '3', '8', '2', 'E',
                                                   '9', 'F', '2', 'B', '4',
                                                   'D', '0', '8', '5', 'E',
                                                   'B', '9', '5', '0', 'C',
                                                   '7', 'A', 'B', '1', '2',
                                                   'E', 'D', 'E', '2', 'D',
                                                   '4', '1', '2', '9', '7',
                                                   '8', '2', '0', 'E', '6',
                                                   '3', '7', '7', 'A', '5',
                                                   'F', 'E', 'B', '5', '6',
                                                   '8', '9', 'D', '4', 'E',
                                                   '6', '0', '3', '2', 'F',
                                                   '6', '0', 'C', '4', '3',
                                                   '0', '7', '4', 'A', '0',
                                                   '4', 'C', '2', '6', 'A',
                                                   'B', '7', '2', 'F', '5',
                                                   '4', 'B', '5', '1', 'B',
                                                   'B', '4', '6', '0', '5',
                                                   '7', '8', '7', '8', '5',
                                                   'B', '1', '9', '9', '0',
                                                   '1', '4', '3', '1', '4',
                                                   'A', '6', '5', 'F', '0',
                                                   '9', '0', 'B', '6', '1',
                                                   'F', 'C', '2', '0', '1',
                                                   '6', '9', '4', '5', '3',
                                                   'B', '5', '8', 'F', 'C',
                                                   '8', 'B', 'A', '4', '3',
                                                   'E', '6', '7', '7', '6',
                                                   'E', 'B', '7', 'E', 'C',
                                                   'D', '3', '1', '7', '8',
                                                   'B', '5', '6', 'A', 'B',
                                                   '0', 'F', 'A', '0', '6',
                                                   'D', 'D', '6', '4', '9',
                                                   '6', '7', 'C', 'B', '1',
                                                   '4', '9', 'E', '5', '0',
                                                   '2', '0', '1', '1', '1'
                                                   , '\0'};

const char *__MCC_libalgo_name_data = "libalgo";

const char *__MCC_libalgo_root_data = "";

const unsigned char __MCC_libalgo_session_data[] = {'A', 'A', '0', 'A', '6',
                                                    'C', '5', 'C', 'F', 'B',
                                                    '5', 'A', 'C', '4', '9',
                                                    '5', '0', 'B', '3', '2',
                                                    '6', 'F', 'C', '8', '8',
                                                    '1', '9', '1', '3', 'D',
                                                    '1', '0', 'D', '3', '3',
                                                    '8', 'D', 'B', 'A', '8',
                                                    '8', '6', '0', 'B', 'B',
                                                    '2', '3', '6', '2', '3',
                                                    '5', '7', 'A', 'B', '4',
                                                    'C', '9', 'D', 'B', '0',
                                                    'A', '6', '4', 'B', '7',
                                                    '2', 'C', '4', '8', 'C',
                                                    'D', '5', 'E', '7', 'A',
                                                    '9', 'D', '4', '0', 'B',
                                                    '6', 'E', '4', '9', 'A',
                                                    'F', '3', '1', 'C', 'D',
                                                    'A', '5', 'C', 'F', '5',
                                                    'E', 'D', 'C', 'B', '9',
                                                    '6', 'E', '2', '3', 'F',
                                                    '0', '9', '0', '7', 'D',
                                                    'C', '1', 'E', 'E', 'B',
                                                    'D', '4', '7', 'C', '1',
                                                    '3', '9', 'E', 'F', '7',
                                                    '5', '1', 'A', '1', '7',
                                                    'C', 'B', '1', 'F', '3',
                                                    '1', 'E', 'F', '1', '4',
                                                    '8', 'A', 'E', '0', '1',
                                                    '0', 'D', '3', '1', '4',
                                                    '4', 'D', 'A', '1', 'F',
                                                    '9', 'E', 'A', '3', '8',
                                                    'E', '2', '9', 'F', '8',
                                                    '8', '5', '0', '5', '6',
                                                    'C', '5', '9', '8', 'A',
                                                    '4', 'C', '2', 'F', 'E',
                                                    'E', 'C', 'C', '6', '7',
                                                    'F', '8', '3', 'E', 'D',
                                                    'C', 'F', 'D', '6', '4',
                                                    '4', '7', '2', '2', '7',
                                                    '3', 'B', 'F', '8', '6',
                                                    '9', 'C', '8', '6', 'E',
                                                    'F', 'C', 'A', 'E', '3',
                                                    '2', '7', '5', 'E', '3',
                                                    '3', '7', '6', '1', '1',
                                                    '4', '7', '0', '5', 'B',
                                                    '0', '1', '5', 'A', '4',
                                                    '6', 'E', '5', '6', '9',
                                                    'D', 'E', '2', '4', '3',
                                                    '5', '8', '5', '9', 'E',
                                                    'A', '0', '8', 'C', '4',
                                                    '8', '\0'};

const char *__MCC_libalgo_matlabpath_data[] = {"libalgo/",
                                               "toolbox/compiler/deploy/",
                                               "$TOOLBOXMATLABDIR/general/",
                                               "$TOOLBOXMATLABDIR/ops/",
                                               "$TOOLBOXMATLABDIR/lang/",
                                               "$TOOLBOXMATLABDIR/elmat/",
                                               "$TOOLBOXMATLABDIR/elfun/",
                                               "$TOOLBOXMATLABDIR/specfun/",
                                               "$TOOLBOXMATLABDIR/matfun/",
                                               "$TOOLBOXMATLABDIR/datafun/",
                                               "$TOOLBOXMATLABDIR/polyfun/",
                                               "$TOOLBOXMATLABDIR/funfun/",
                                               "$TOOLBOXMATLABDIR/sparfun/",
                                               "$TOOLBOXMATLABDIR/scribe/",
                                               "$TOOLBOXMATLABDIR/graph2d/",
                                               "$TOOLBOXMATLABDIR/graph3d/",
                                               "$TOOLBOXMATLABDIR/specgraph/",
                                               "$TOOLBOXMATLABDIR/graphics/",
                                               "$TOOLBOXMATLABDIR/uitools/",
                                               "$TOOLBOXMATLABDIR/strfun/",
                                               "$TOOLBOXMATLABDIR/imagesci/",
                                               "$TOOLBOXMATLABDIR/iofun/",
                                               "$TOOLBOXMATLABDIR/audiovideo/",
                                               "$TOOLBOXMATLABDIR/timefun/",
                                               "$TOOLBOXMATLABDIR/datatypes/",
                                               "$TOOLBOXMATLABDIR/verctrl/",
                                               "$TOOLBOXMATLABDIR/codetools/",
                                               "$TOOLBOXMATLABDIR/helptools/",
                                               "$TOOLBOXMATLABDIR/winfun/",
                                               "$TOOLBOXMATLABDIR/demos/",
                                               "toolbox/local/",
                                               "toolbox/compiler/",
                                               "toolbox/signal/signal/"};
const int __MCC_libalgo_matlabpath_data_count = 33;

const char *__MCC_libalgo_mcr_application_options[] = { "" };
const int __MCC_libalgo_mcr_application_option_count = 0;
const char *__MCC_libalgo_mcr_runtime_options[] = { "" };
const int __MCC_libalgo_mcr_runtime_option_count = 0;
#ifdef __cplusplus
}
#endif


