###########################################################################
#
# Generated by : Version 8.0 Build 231 07/10/2008 Service Pack 1 SJ Full Version
#
# Project      : top
# Revision     : top
#
# Date         : Wed May 04 20:53:13 China Standard Time 2011
#
###########################################################################
 
 
# WARNING: Expected ENABLE_CLOCK_LATENCY to be set to 'ON', but it is set to 'OFF'
#          In SDC, create_generated_clock auto-generates clock latency
#
# ------------------------------------------
#
# Create generated clocks based on PLLs
derive_pll_clocks -use_tan_name
#
# ------------------------------------------


# Original Clock Setting Name: usb_clk
create_clock -period "22.222 ns" \
             -name {FX_CLK_i} {FX_CLK_i}
# ---------------------------------------------


# Original Clock Setting Name: lvds_i:lvds_i_1|rx_inclock
create_clock -period "5.000 ns" \
             -name {rx_inclock_i} {rx_inclock_i}
# ---------------------------------------------

# ** Clock Latency
#    -------------

# ** Clock Uncertainty
#    -----------------

# ** Multicycles
#    -----------
# ** Cuts
#    ----

# ** Input/Output Delays
#    -------------------


set_output_delay -clock { dcm45:dcm45_ssram|altpll:altpll_component|_clk0 } -min 0 [get_ports {data_o*}]
set_output_delay -clock { dcm45:dcm45_ssram|altpll:altpll_component|_clk0 } -max 2.0 [get_ports {data_o*}]


# ** Tpd requirements
#    ----------------

# ** Setup/Hold Relationships
#    ------------------------

# ** Tsu/Th requirements
#    -------------------


# ** Tco/MinTco requirements
#    -----------------------



# ---------------------------------------------
# The following clock group is added to try to 
# match the behavior of:
#   CUT_OFF_PATHS_BETWEEN_CLOCK_DOMAINS = ON
# ---------------------------------------------

set_clock_groups -asynchronous \
                 -group { \
                       dcm45:dcm45_ssram|altpll:altpll_component|_clk0 \
                       rx_inclock_i \
                        } \
                 -group { \
                       tlc3548:tlc3548_1|dcm_1M:dcm_1M_1|altpll:altpll_component|_clk0 \
                       dcm_user:dcm_user_1|altpll:altpll_component|_clk0 \
                       FX_CLK_i \
                        } \

# ---------------------------------------------

