--
-- VHDL Architecture Std_Lib.shiftreg_en_pline.spec
--
-- Created:
--          by - daebischer.UNKNOWN (PC-57)
--          at - 12:57:50 01/23/03
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2002.1 (Build 143)
--
library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;

-- dff en pipeline avec Enable et reset
--
-- Le nombre de pipeline estb défini par le générique pipeline
entity dff_en_r_pline is
  generic(
    Pipeline : integer := 8
    );
  port(
    CK     : in  std_logic;
    Clear  : in  std_logic := '0';
    Data   : in  std_logic;
    Enable : in  std_logic := '1';
    Q      : out std_logic
    );

-- Declarations

end dff_en_r_pline;
architecture spec of dff_en_r_pline is
  type   t_int_reg is array (0 to Pipeline) of std_logic;
  signal int_reg : t_int_reg;
begin
  ShReg : process (Ck, Clear)
  begin
    if Clear = '1' then
      for i in 0 to Pipeline loop
        int_reg(i) <= '0';
      end loop;
    elsif rising_edge(Ck) then
      if Enable = '1' then
        int_reg(Pipeline)        <= Data;
        int_reg(0 to Pipeline-1) <= int_reg(1 to Pipeline);
      end if;
    end if;
  end process ShReg;
  Q <= int_reg(0);
end spec;

